### ISSUE TITLE
Order of INF_MICRO_FLX and B1_MICRO_FLX in *_res.m file

### ISSUE THREAD

**Issue by travleev** [CORE-GATECH-GROUP/serpent-tools#350] opened 2019-10-10 12:06 UTC
## Summary of issue
Serpent2 prints in the resulting file ``*_res.m`` the ``INF_MICRO_FLX`` and ``B1_MICRO_FLX`` arrays in the order that differs from the order of ``MICRO_E``. This peculiarity is not taken into account by the ``HomogUniv.plot()`` method so that the generated plots are irrelevant.

I think this is actually the Serpent's issue and [reported](https://ttuki.vtt.fi/serpent/viewtopic.php?f=11&t=3226) it as a bug. However, a workaround in ``serpentTools`` would be helpful untill this behaviuor is fixed in Serpent.

## Code for reproducing the issue
The following Serpent2 (tested with 2.1.29 and 2.1.31)  [input file](https://github.com/CORE-GATECH-GROUP/serpent-tools/files/3712355/i1.inp.txt) describes a thermal multiplying system, where the infinite and B1 critical fluxes are calculated:
```
set acelib sss_endfb7u.xsdata

surf s1 sqc 0 0 10.0

cell c1 0 unat -s1
cell c3 0 outside s1 

mat unat -10.0
    92235.03c  -5.00
    92238.03c -95.00
     1001.03c  -0.5

set bc 2
set pop 1000 100 20 
set fum 
```

The follwing script reads the [resulting file](https://github.com/CORE-GATECH-GROUP/serpent-tools/files/3712359/i1.inp.txt_res.m.txt) and generates 3 plots: the upper with the ``HomogUniv.plot()`` method, the lower two -- by using the reverse-sorted flux arrays. The plots are in the attached [plt_micro_flx.pdf](https://github.com/CORE-GATECH-GROUP/serpent-tools/files/3712326/plt_micro_flx.pdf) and repeated in the section below.

```Python 

import serpentTools
import numpy as np
import matplotlib.pyplot as plt

fname = 'i1.inp.txt_res.m'  # *_res.m file to read

# Read *_res.m with serpentTools
r = serpentTools.read(fname)
n = r.universes.keys()[0][0]  # get the universe name, assuming that all entries in universes correspond to the same universe name.
u = r.universes[(n, 0, 0, 0)]

f, (a1, a2, a3) = plt.subplots(nrows=3, figsize=(5, 12), sharex=True)

# Standard plot MICRO_FLX, using plot() method
a1 = u.plot('infMicroFlx', ax=a1, labels=['inf'])
a1 = u.plot('b1MicroFlx', ax=a1, labels=['b1'])
a1.set_title('serpentTools plot')

# Prepare plot data manually
imf = u.infExp['infMicroFlx']  # INF_MICRO_FLX
bmf = u.b1Exp['b1MicroFlx']    # B1_MICRO_FLX

imf = imf[::-1]  # reverse arrays!
bmf = bmf[::-1]

e = u.microGroups
de = e[1:] - e[0:-1]           # Energy group widths

a2.step(e[1:], imf, where='post', label='inf')
a2.step(e[1:], bmf, where='post', label='b1')

a3.step(e[1:], imf/de, where='post', label='inf / dE')
a3.step(e[1:], bmf/de, where='post', label='b1 / dE')

a2.set_title('Reversed flux')
a3.set_title('Reversed flux per unit energy')

for a in (a1, a2, a3):
    a.set_xscale('log')
    a.set_yscale('log')
    a.legend()

f.savefig('plt_micro_flx.pdf')
```

## Actual outcome including console output and error traceback if applicable
![plt_micro_flx](https://user-images.githubusercontent.com/8748313/66566775-156a7280-eb66-11e9-9da9-4e4272b12b9d.png)
## Expected outcome
On the above figure, the lowest plot shows the well-known spectrum (neutron flux per unit enertgy) of a thermal system. The correspondent unnormalized flux is shown on the middle plot. 

## Versions

* Version  from ``serpentTools.__version__``
``0.7..0+2.gabd562e.dirty``

* Python version - ``python --version``
``Python 2.7.11 :: ANaconda custom (64-bin)``
* IPython or Jupyter version if applicable

**Comment by drewejohnson** [comment] 2019-10-10 13:07
Thank you for bringing this to our attention. I have been able to reproduce this with your input file, and made the flux plot with detector as well. 

The easy fix, if you want to use the `univese.plot` method, is to reverse the `microGroups` attribute
```
u.microGroups = u.microGroups[::-1]
u.plot("infMicroFlux", loglog=True, ylabel="Micro flux")
```
![microflux](https://user-images.githubusercontent.com/19477741/66570906-85fc9980-eb3c-11e9-8c30-416ef475059d.png)

The longer-term fix is less clear. Since this appears to originate from a Serpent bug, I would like to see how they decide to fix the issue first. We may have to put a version check when passing `microGroups` if this is fixed in future Serpent versions.

**Comment by drewejohnson** [comment] 2019-10-11 17:00
Looks like the Serpent team has confirmed this is a bug on their end. I'm going to close this because the simple workaround is easy, and I don't want to introduce a fix that may compete with future versions.

**Closed by drewejohnson** 2019-10-11 17:00 UTC
