### ISSUE TITLE
Problem with parsing detector names

### ISSUE THREAD

**Issue by Olivercomputing** [CORE-GATECH-GROUP/serpent-tools#389] opened 2020-03-23 01:13 UTC
## Summary of issue

Detector output containing detector names 'assembly1_UO2' and 'assembly1_UO2Gd' fails to pick up the second named output.

## Code for reproducing the issue

I don't have a minimal test case so far, I can't post the actual one because it's proprietary.

## Expected outcome

Both named detector outputs should be parsed correctly. Changing 'assembly1_UO2Gd' to 'assembly1_GdUO2' causes apparently correct behavior. My surmise is that having a name which is a subset of longer name causes the longer one to be skipped in some way.

## Versions
Latest and the previous one.

**Comment by drewejohnson** [comment] 2020-03-24 21:18
Thanks for bringing this to our attention! (and my apologies for not seeing this until now)

This seems very similar to #374 which was due to the detector parsing. This __should__ have been fixed with version [0.9.2](https://serpent-tools.readthedocs.io/en/latest/changelog.html#bug-fixes), but you say you're on the latest version. Strange indeed...

If you cannot provide additional information, can you use one of our test files to reproduce the issue? [`bwr_det0.m`](https://raw.githubusercontent.com/CORE-GATECH-GROUP/serpent-tools/develop/data/bwr_det0.m) might be a good candidate. There are some shell commands in the linked issue that may be helpful.

**Comment by drewejohnson** [comment] 2020-03-31 00:24
@Olivercomputing any luck on this? I'm gearing up to make one final bug fix release before the next development phase and would like to fix / resolve this

**Comment by drewejohnson** [comment] 2020-04-07 19:06
Closing this as a potential duplicate of #374, and I haven't been able to reproduce with 0.9.2. If you still experience the issue, please let me know.

**Closed by drewejohnson** 2020-04-07 19:06 UTC
Labels: bug
